chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.chats, name='chats'),
    path('room/<int:user1_id>/<int:user2_id>/', views.room_view, name='room'),
    path('checkview/<int:userid>/', views.check_view, name='check_view'),
]

home/urls.py
from django.urls import path, re_path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'detail/(?P<id>[0-9]+)/(?P<slug>[-\w]+)/', views.detail, name='ad_detail'),
    path("search_result/", views.search_result, name='search result'),
    path("my_advertises/", views.my_advertises, name='my advertises'),
    path("add_advertise/", views.add_advertise, name='add advertise'),
    path("edit_resume/<str:username>", views.edit_resume, name='edit resume'),
    path("resume_detail/<int:user_id>", views.resume_detail, name='resume detail'),
]

jobSearch/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('account/', include('account.urls')),
    path('chat/', include('chat.urls')),
    path('about/', include('about.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from advertising.models import Advertise
from advertising.forms import AddAdvertiseForm, EditResumeForm
from account.models import User
from chat.models import Room


def home(request):
    advertise = Advertise.objects.filter(status='p').order_by('-publish')
    resumes = User.objects.filter(type_of_user='1')
    return render(request, 'home/home.html', context={'ad': advertise, 'resumes': resumes})


def detail(request, id, slug):
    ad_detail = get_object_or_404(Advertise, id=id, slug=slug)
    return render(request, 'home/detail.html', context={'advertise': ad_detail})


def search_result(request):
    q = request.GET.get('q')
    ads = Advertise.objects.filter(title__icontains=q, status='p').order_by('-publish')
    resumes = User.objects.filter(skill__icontains=q, type_of_user='1')
    return render(request, 'home/home.html', context={'ad': ads, 'resumes': resumes})


def my_advertises(request):
    ads = Advertise.objects.filter(user_id=request.user.id, status='p').order_by('-publish')
    return render(request, 'home/home.html', context={'ad': ads})


def add_advertise(request):
    user = request.user
    if user.is_authenticated:
        if request.method == 'POST':
            form = AddAdvertiseForm(request.POST, request.FILES)
            if form.is_valid():
                instance = form.save(commit=False)
                instance.user = request.user
                instance.save()
                return redirect('home:my advertises')
        else:
            form = AddAdvertiseForm()
        return render(request, 'home/advertise.html', context={'form': form})
    else:
        return redirect('home:home')


def edit_resume(request, username):
    the_user = User.objects.get(username=username)
    user = request.user
    if the_user.type_of_user == '1' and user.is_authenticated:
        if the_user.username == user.username:
            form = EditResumeForm(instance=user)
            if request.method == 'POST':
                form = EditResumeForm(instance=user, data=request.POST)
                if form.is_valid():
                    form.save()
                    return redirect('home:home')
            return render(request, "home/Resume.html", context={'form': form, 'the_user': the_user})
        else:
            return redirect('home:home')
    else:
        return redirect('home:home')


def resume_detail(request, user_id):
    user_resume = User.objects.get(id=user_id, type_of_user='1')
    return render(request, 'home/Resumedetail.html', context={'user_resume': user_resume})

home/templates/home/Resume.html
<!DOCTYPE html>

<html>
<head>
<style>
body {
font-family: Arial;
  direction:rtl;
}
* {
box-sizing: border-box;
}
.container {
width: 100%;
padding: 16px;
background-image:url(Background.jpg);
background-repeat:no-repeat;
background-atachment:fixed;
background-size:cover;
border: 1px solid #333;
}
input{
width: 100%;
padding: 15px;
margin: 5px 0 22px 0;
display: inline-block;
border: none;
background: #f1f1f1;
}
input:focus{
background-color: #ddd;
outline: none;
}
hr {
border: 1px solid #f1f1f1;
margin-bottom: 25px;
}
.registerbtn {
background-color:lightskyblue;
color: black;
padding: 15px;
margin: 8px 0;
border: none;
cursor: pointer;
width: 100%;
opacity: 0.9;
opacity: 1;
}
a {
color: black;
}
  .logo{
    height:63px;
    width:100%;
    background-color:lightskyblue;
  }
  .ertebat{
    height:60px;
    width:100%;
    background-color:lightskyblue;
    padding-right:5px;
  }
  footer{
    font-size:0.5px;
  }
</style>
</head>
<body>
  <header>
    <div class="logo">
<a href="menu.html"> <img src="menu.png" width="42" height="50" style="padding-right:8px; padding-top:6px;"> </a>
 <img src="logo.jpg" width="225" height="50">
<a href="search.html"><img src="search.png" width="42" height="50"></a>
    </div>
  </header>
  <div>
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">تمام</button>
    </form>
</div>
  <footer>
  <div class="ertebat">
    <h3>ارتباط با ما</h3>
   <p>پشتیبانی کار جویان 05137474747</p>
   <p>پشتیبانی کار فرمایان05137676767</p>
  </div>
</footer>
</body>
</html>

home/templates/home/Resumedetail.html
<!DOCTYPE html>

<html>
<head>
<style>
body {
font-family: Arial;
  direction:rtl;
}
* {
box-sizing: border-box;
}
.container {
width: 100%;
padding: 16px;
background-image:url(Background.jpg);
background-repeat:no-repeat;
background-atachment:fixed;
background-size:cover;
border: 1px solid #333;
}
input{
width: 100%;
padding: 15px;
margin: 5px 0 22px 0;
display: inline-block;
border: none;
background: #f1f1f1;
}
input:focus{
background-color: #ddd;
outline: none;
}
hr {
border: 1px solid #f1f1f1;
margin-bottom: 25px;
}
.registerbtn {
background-color:lightskyblue;
color: black;
padding: 15px;
margin: 8px 0;
border: none;
cursor: pointer;
width: 100%;
opacity: 0.9;
opacity: 1;
}
a {
color: black;
}
  .logo{
    height:63px;
    width:100%;
    background-color:lightskyblue;
  }
  .ertebat{
    height:60px;
    width:100%;
    background-color:lightskyblue;
    padding-right:5px;
  }
  footer{
    font-size:0.5px;
  }
</style>
</head>
<body>
  <header>
    <div class="logo">
<a href="menu.html"> <img src="menu.png" width="42" height="50" style="padding-right:8px; padding-top:6px;"> </a>
 <img src="logo.jpg" width="225" height="50">
<a href="search.html"><img src="search.png" width="42" height="50"></a>
    </div>
  </header>
  <div>
<div class="container" style="font-size: 20px">
    <br>
<span>نام:</span>
<span>{{ user_resume.full_name }}</span><br><br>
<span>ایمیل:</span>
<span>{{ user_resume.email }}</span><br><br>
<span>شماره مبایل:</span>
<span>{{ user_resume.phone }}</span><br><br>
<span>حرفه:</span>
<span>{{ user_resume.skill }}</span>  <br><br>
<span>وضعیت تاهل:</span>
<span>{{ user_resume.status }}</span> <br><br>
<span>مقطع تحصیلی:</span>
<span>{{ user_resume.education }}</span><br><br>
<span>دانشگاه:</span>
<span>{{ user_resume.university }}</span><br><br>
<span>رشته:</span>
<span>{{ user_resume.field }}</span><br><br>
<span>تسلط به انگلیسی:</span>
<span>{{ user_resume.english }}</span><br><br>
<span>تسلط به زبان دیگر:</span>
<span>{{ user_resume.language }}</span><br><br>
<span>پروژه های:</span>
<span>{{ user_resume.project }}</span><br><br>
<span>گواهی نامه و افتخارات:</span>
<span>{{ user_resume.certificate }}</span><br><br>
<span>دوره ها:</span>
<span>{{ user_resume.courses }}</span><br><br>
<span>تجربه شغلی:</span>
<span>{{ user_resume.job }}</span><br><br>
<span>آخرین موقعیت شغلی:</span>
<span>{{ user_resume.last_job_situation }}</span><br><br>
<span>شهر:</span>
<span>{{ user_resume.city }}</span><br><br>
    {% if request.user.id != user_resume.id %}
        <p><a href="{% url 'chat:check_view' request.user.id user_resume.id %}">چت با کاربر</a></p>
    {% endif %}
</div>
  <footer>
  <div class="ertebat">
    <h3>ارتباط با ما</h3>
   <p>پشتیبانی کار جویان 05137474747</p>
   <p>پشتیبانی کار فرمایان05137676767</p>
  </div>
</footer>
</body>
</html>

home/templates/home/advertise.html
<!DOCTYPE html>
<html>
<head>
<style>
body {
font-family: Arial;
  direction:rtl;
}
* {
box-sizing: border-box;
}
.container {
width: 100%;
padding: 16px;
background-image:url(Background.jpg);
background-repeat:no-repeat;
background-atachment:fixed;
background-size:cover;
border: 1px solid #333;
}
input{
width: 100%;
padding: 15px;
margin: 5px 0 22px 0;
display: inline-block;
border: none;
background: #f1f1f1;
}
input:focus{
background-color: #ddd;
outline: none;
}
hr {
border: 1px solid #f1f1f1;
margin-bottom: 25px;
}
.registerbtn {
background-color:rgb(7, 51, 79);
color: rgb(255, 255, 255);
padding: 15px;
margin: 8px 0;
border: none;
cursor: pointer;
width: 100%;
opacity: 0.9;
opacity: 1;
}
a {
color: black;
}
  .logo{
    height:63px;
    width:100%;
    background-color:rgb(7, 51, 79);
  }
  .ertebat{
    height:60px;
    width:100%;
    background-color:rgb(7, 51, 79);
    padding-right:5px;
    color:white;
  }
  footer{
    font-size:0.5px;
  }
</style>
</head>
<body>
  <header>
    <div class="logo">
  </div>
  </header>
              <!-- Content -->
              <div id="content" class="colM">
                
                <h1>اضافه کردن آگهی</h1>
                
                <div id="content-main">


                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form }}
                        <div class="">
                            <button type="submit" class="btn custom-btn w-50">ثبت</button>
                        </div>
                        <hr>
                        {{ form.errors }}
                        {{ form.non_field_errors }}



                    </form>
      
                
                <br class="clear">
              </div>
              <!-- END Content -->
              <div id="footer"></div>
            </div>
          </div>
      </div>
      <!-- END Container -->
      </body>
      </html>
  <footer>
  <div class="ertebat">
    <h3>ارتباط با ما</h3>
   <p>پشتیبانی کار جویان 05137474747</p>
   <p>پشتیبانی کار فرمایان05137676767</p>
  </div>
</footer>
</body>
</html>

home/templates/home/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ advertise.title }}
{% endblock %}
{% block main %}    
    <!-- Detail Start -->
    <div class="container py-5" dir="rtl">
        <div class="row pt-5">
            <div class="col-lg-8">
                <div class="d-flex flex-column text-left mb-3">
                    <p class="section-title pr-5"><span class="pr-2">Blog Detail Page</span></p>
                    <h1 class="mb-3" style="text-align: right">{{advertise.title}}</h1>
                    <div class="d-flex">
                        <p class="mr-3"><i class="fa fa-user text-primary"></i> {{ advertise.user }}</p>
                        <p class="mr-3"><i class=""></i> {{ advertise.city }}</p>
                        <p class="mr-3"><i class="fa date-back"></i> {{ advertise.create }}</p>
                    </div>
                </div>
                <div class="mb-5" style="text-align: right">
                    <img class="img-fluid rounded w-100 mb-4" src="{{advertise.thumbnail.url}}" alt="Image">
                    <p>{{advertise.description|linebreaks}}</p>
                    {% if request.user.id != advertise.user.id %}
                        <p><a href="{% url 'chat:check_view' advertise.user.id %}">چت با کاربر</a></p>
                    {% endif %}
                </div>
            </div>   
        </div>
    </div>

    <script type="text/javascript">

    </script>
    <!-- Detail End -->
{% endblock %}

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
home
{% endblock %}
{% block main %}
<!-- Blog Start -->
        <div class="row" style="text-align: right; direction: rtl; margin-top: 50px">
        {% for art in ad %}
            <div class="col-lg-4 mb-4">
                <div class="card border-0 shadow-sm mb-2">
                    <img class="card-img-top mb-2" src="{{art.thumbnail.url}}" alt="" height="200" title="{{art.title}}">
                    <div class="card-body bg-light text-center p-4">
                        <h4 class="">{{art.title}}</h4>
                        <div class="d-flex justify-content-center mb-3">
                            <small class="mr-3"><i class="fa fa-clock text-primary"></i> {{art.publish}}</small>
                        </div>
                        <p>{{art.description|truncatewords:30}}</p>
                        <p>
{#                          {% for cat in art.category.all %}#}
{#                          <a href="{% url 'blog:category' cat.slug %}">{{cat.title}}#</a>#}
{#                          {% endfor %}#}
                        </p>
                        <a href="{{ art.get_absolute_url }}" class="btn btn-primary px-4 mx-auto my-2">Read More</a>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div style="height: 100px; width: 100%; background-color: rgb(31, 85, 119);">
                <div class="text-center pb-2">
                    <h1 style="padding:50px; color: rgb(255, 255, 255)">رزومه ها </h1>
                </div>
            </div>
            {% for resume in resumes %}
            <div class="col-lg-4 mb-4">
                <div class="card border-0 shadow-sm mb-2">
                    {% if resume.image %}
                        <img style="border-radius: ;" class="card-img-top mb-2" src="{{resume.image.url}}" alt="" height="200" title="{{resume.username}}">
                    {% else %}
                        <img class="card-img-top mb-2" src="{% static 'img/student-prof.png' %}" alt="" height="200" title="{{resume.username}}">
                    {% endif %}
                    <div class="card-body bg-light text-center p-4">
                        <h4 class="">{{resume.full_name}}</h4>
                        <div class="d-flex justify-content-center mb-3">
                            <small class="mr-3"><i class="fa fa-clock text-primary"></i> {{ resume.city }}</small>
                        </div>
                        <p>{{ resume.skill }}</p>
                        <a href="{% url 'home:resume detail' resume.id %}" class="btn btn-primary px-4 mx-auto my-2">Read More</a>
                    </div>
                </div>
            </div>
            {% endfor %}
       
<!-- Blog End -->
{% endblock %}